name: langchain-aws-slack-bot-rag
channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - aws-cdk-lib
    - langchain==0.0.239
    - boto3
    - requests
    - openai
    - slack_sdk
